### PR TITLE
Constellation

### PR DESCRIPTION
**Pull request by SahyadriDK**
Please tell me if the current form of const_data.json works for you. The data has not been matched to any hyg.json file yet, so please do not treat this as a final data file. Do not plot this as the coordinates will be inaccurate. This pull request is to check if the const_data.json is in a form that you can use.

### CODE REVIEW

**Review by chichengren — COMMENTED** [review]
@SahyadriDK It seems like the json file itself is not in valid json format. can we fix that before merging this PR?

**Comment by SahyadriDK** [comment]
@chichengren Thanks. I'll fix that ASAP.

**Comment by SahyadriDK** [comment]
@chichengren Sorry for asking, but what json format are you looking for? I used json.dumps and writing that to a file. Do you require a dictionary structure?

`string = json.dumps(coord)
 output.write('{}\n'.format(string)) #output is the file I'm writing to`

**Comment by chichengren** [comment]
> @chichengren Sorry for asking, but what json format are you looking for? I used json.dumps and writing that to a file. Do you require a dictionary structure?
> 
> `string = json.dumps(coord) output.write('{}\n'.format(string)) #output is the file I'm writing to`

@SahyadriDK I think the current json data structure looks fine to me. It would be even better if we can have each coordinate as a tuple and then each constellation would be an array of such tuple (tuple could be presented in an array), something like:

`
{
  constellations: [
    [[long1, lat1], [long2, lat2], ...], // first constellation
    [[long3, lat3], [long4, lat4], ...], // second constellation
    ...
 ]
}
` 

Let me know if this example makes sense to you. Meantime, I will approve this PR to unblock you from merging. Please do let me know which data structure you go with.

**Review by chichengren — APPROVED** [review]
LGTM

**Comment by Pycomet-zz** [comment]
@SahyadriDK Having the constellation interpreted in tuples within the dictionary JSON file would be the best/easiest way the UI would be able to interprete the coordinates. I will approve the PR too so you can merge what we have here already

**Comment by SahyadriDK** [comment]
@Pycomet @chichengren Thanks for the suggestions! I'll get to implementing it.

**Pull request merged**
